= Setup Quarkus Github Discussions to enable the broader Community

* Status: proposed
* Date: 2021-06-26

== Context and Problem Statement

Quarkus community is growing and until now we've catered very well for core contributors and initial early consumers. 

We have multiple communication channels: https://github.com/quarkusio/quarkus[issues], https://groups.google.com/g/quarkus-dev?pli=1[quarkus-dev mailing list], https://quarkusio.zulipchat.com[zulip], https://stackoverflow.com/questions/tagged/quarkus[stackoverflow]

Isues are great for bugs/feature work. Mailing list for design conversations between developers, chat for watercooler style discussions and stackoverflow for user questions.

This setup has issues though, some are:

- zulip chat is used for a lot of users questions but none of that is easily searchable/discoverable so it is very synchronous,
- people reported that they don't feel okey posting on quarkus-dev or zulips as it is seems focused on dev work and not so much about community events, jobs, conferences, etc.
- its hard to monitor as contributor who wants to help answer/ask questions.

How can we improve this situaton and enable the broader community to more easily ask questions and find answers - without it all be relying on just a few Quarkus core contributors?

== Scenarios (optional)

User wants to locate a answer to a question - zulip chats does not show up in google search; stackoverflow might but might not have an answer.

Contributor want to arrange or attend an event around Quarkus - where do he post/look for info on that ?

Contributor/committer are trying to follow new questions and issues - what does he need to track to do that ? today it is alot and it is all different notification sytems and mainly its a big "firehose" with no good ability to filter out what you don't need.

User looking for a job involving Quarkus - where do he go look ?


////
 as well as a lot of social platform presence https://twitter.com/quarkusio/[twitter], https://www.facebook.com/quarkusio/[facebook], https://www.linkedin.com/groups/13789086/[linkedin], https://www.youtube.com/quarkusio[youtube] and https://www.linkedin.com/groups/13789086/[reddit].
////

== Considered options

* stackoverflow will not go away - thus for this current proposal it does not include Q/A section.
* "I can't track more places" is a very valid worry; the advantage of discussions is that it shows up in your normal github notifcations which you can mute, filter,etc. like anything else on Github. Thus it gives you more control rather than just adding more noise.

=== quarkusio-community mailing list
Not proposed since it is just another waterhose of info with no good ability to ignore/consume as needed/wanted.

=== enable discussions on github.com/quarkusio/quarkus-insights
Considered as quarkus insights is an existing "community" and let us have separate permissons for moderators/triage but some suggested it might be hard to find.

=== enable discussions on github.com/quarkusio/community
Downside is that labels etc. would need to be kept in sync and that searches in github.com/quarkusio would not show up community/discussions.
It could show up if searched on github.com/quarkus level though.
Could be considered as allow us to have separate permissions for moderator/triagers separate from commit access - need to check if https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization[github docs] on permissions levels work for us.

== Decision

Enable GitHub discussions feature on `quarkusio/quarkusio` with the following initial categories:

- Announcements (post only by admins)
- Quarkus Comunity (post by anyone, general discussions)
- Quarkus Insights Episodes (show notes and offline comments)
- Quarkus World Tour and other Events (Setup and announce of interest or other events)
- Jobs and Opportunities (post by anyone)

== Consequences

With this the conversation(s) in Quarkus community is no longer only about development on quarkus-dev mailing list nor  just by Quarkus core contributors. That should enable broader participation and let Quarkus community grow beyond just "the code".

We don't (yet) add a Q/A section to this as Zulip Users and Stackoverflow still exist.

Downsides: "Another notification sinkhole"; yes - it is another additional location to keep an eye on but since this is hosted at Github you can use the unified notifcation mechanism and system; especially you can just subscribe or unsubrcibe based on  what is best for the invidiual community member.

